### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by jonorozcoc** [nylo-core/nylo#10]
The readme requirements are different to the website's one:

Repo readme:
![image](https://user-images.githubusercontent.com/8442497/132077117-5fc3dfe9-7b55-4253-a95d-e1578b70be0f.png)

Website requirements page:
![image](https://user-images.githubusercontent.com/8442497/132077142-c53f3742-3770-4b5d-8be0-53d1d40a77ff.png)

**Comment by agordn52** [comment]
Thanks, all resolved in this commit https://github.com/nylo-core/nylo/commit/2794d5bc7692d2603d1f40db6caaaa2a47268281
