### ISSUE TITLE
widget.data() still have data

### ISSUE THREAD

**Issue by jitendravn** [nylo-core/nylo#100]
assume i have 3 screen
1 and 2 have relation between 
example screen 1 is listing page
and 2 has view page 
but if come 2 screen using 3rd screen
still widget.data() hold a value

**Comment by agordn52** [comment]
Hi @jitendravn, 

Which `nylo_framework` version are you using?
In the latest version, you can set if the controller should retain the data.

**Comment by jitendravn** [comment]
I am having 3 screens - Screen 1, Screen 2 and Screen 3. I am using routeTo to send data to next screen.
routeTo(PATH, data: SCREEN DATA);
On next screen, I am using widget.data() to consume data from previous screen. Its working fine with sending data to the next/landing screen (example Screen 2 to Screen 3).
My problem is - Data presisting (sent previously from screen 2), If I am using routeTo without data param from Screen 1 to Screen 3.
Is there any way to clear the widget.data() on dispose()?

**Comment by agordn52** [comment]
Hi @jitendravn,

Thanks for the information but can you confirm which version of the `nylo_framework` you are using?

This can be found in your pubspec.yaml file.

**Comment by jitendravn** [comment]
@agordn52 5.11.0

**Comment by agordn52** [comment]
Hi @jitendravn,

Can you upgrade to the latest (v5.18.7) version?

`nylo_framework: ^5.18.7`

Here's the migration guide [here](https://github.com/nylo-core/nylo/compare/v5.11.0...v5.18.1)

I hope that helps, once you've migrated to the latest version, try rerunning your project.

**Comment by jitendravn** [comment]
hi @agordn52 
I have upgraded my project to the latest version. But I'm facing the same issue

**Comment by agordn52** [comment]
Resolved.

Talked with @jitendravn via Google Meet and discovered his project wasn't updated to the latest (`nylo_framework: ^5.18.7`) version.

**Comment by jitendravn** [comment]
Thanks @agordn52  for the resolving the issue
