### ISSUE TITLE
Nylo future upgrades and maintenance  

### ISSUE THREAD

**Issue by dvsgvarma** [nylo-core/nylo#11]
Since Flutter & Dart releasing frequently i would like to check if we have a way to upgrade Nylo with out braking existing functionality 

For example : 
- Nylo 1.x to 2.x
- Upgrade to dart v2.14.0 
- Any major upcoming releases from flutter

**Comment by agordn52** [comment]
Here's an upgrade guide to 2.x from 1.x https://nylo.dev/docs/2.x/upgrade-guide
Major releases often do introduce some breaking changes, unfortunately.

Most of the improvements have been to the underlying framework and support library.
These changes have forced a major release as they do change API names, methods and more in the base repository.

Check out the upgrade guide above, hope it explains the key areas updated.

Lastly, [v2.0.2](https://github.com/nylo-core/nylo/releases/tag/v2.0.2) has been upgraded to use dart v2.14.0.
