### ISSUE TITLE
Back gesture not working in nylo

### ISSUE THREAD

**Issue by jitendravn** [nylo-core/nylo#110]
Hello Sir @agordn52 , 
when I create a project in Flutter itself. 
the back gesture is working fine.

But in Nylo I'm not able to back by using gesture(finger horizontal swipe)

**Comment by agordn52** [comment]
Hi @jitendravn,

If you want to implement gestures to swipe to the previous page in your project, update the Theme.

Here's an example using `pageTransitionsTheme`.

File: `resources/themes/light_theme.dart`

``` dart
...
return ThemeData(
    useMaterial3: true,
    pageTransitionsTheme: PageTransitionsTheme(
        builders: {
          TargetPlatform.android: CupertinoPageTransitionsBuilder(),
          TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
        }
    ),
```

This isn't an issue with the framework, marking this issue closed  👍

**Comment by jitendravn** [comment]
@agordn52 Thank you, sir

**Comment by wchbrad** [comment]
@agordn52 Sorry to bother you, this solution seems to be unusable now. Usage process:
1. Download the latest nylo master branch;
2. Run after adjusting the ID;
3. Add the above code to both light_theme.dart and dark.dart files
4. 
`ListTile in homePage.dart（
leading: FaIcon(FontAwesomeIcons.readme),
title: Text(
"Documentation",
).bodyLarge(color: context.color.surfaceContent),
subtitle: Text(
"Master the framework",
).bodySmall(color: context.color.surfaceContent),
trailing: const Icon(Icons.chevron_right),
onTap: widget.controller.onTapDocumentation,
）`

Change to 

`ListTile（
leading: FaIcon(FontAwesomeIcons.readme),
title: Text(
"Documentation",
).bodyLarge(color: context.color.surfaceContent),
subtitle: Text(
"Master the framework",
).bodySmall(color: context.color.surfaceContent),
trailing: const Icon(Icons.chevron_right),
onTap: (){
routeTo(AccountPage.path);
},
)`
4. After reloading, when clicking on Documentation, it was found that the left swipe gesture could not be used to return to the previous route
