### ISSUE TITLE
AuthRouteGuard not working when restart application

### ISSUE THREAD

**Issue by tayfunuyar** [nylo-core/nylo#118]
Hi ,
When I restart to application initial page loading and authRouteGuard not working and redirect to auth page. 

````
appRouter() => nyRoutes((router) {
      router.route(AccountPage.path, (context) => AccountPage(),
          authPage: true);
      router.group(
          () => {
                "route_guards": [AuthRouteGuard()],
                "prefix": "/dashboards"
              }, (router) {
        router.route(HomePage.path, (context) => HomePage(),
            initialRoute: true);
        router.route(CashAndBankBalanceReportPage.path,
            (context) => CashAndBankBalanceReportPage());
      });
    });
````

**Comment by agordn52** [comment]
Hi @tayfunuyar,

Route guards are used to protect routes only when navigating to new routes.
In short, they won't be invoked on the initial load, only when navigating to those pages in the app.

Using `routeTo(...)` or `Text("Next Page").onTapRoute` will invoke the route guards to be triggered.
Hope that helps.
