### ISSUE TITLE
Issue in Nystate or may be in nypage

### ISSUE THREAD

**Issue by jitendravn** [nylo-core/nylo#127]
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5579 pos 12: 'state._element == null': is not true.

I have a bottom navigation.Having 4 menu
when i click on 3rd menu
and return back to 1st screen and again click on 3rd menu 
then I got this error

for as of now
I using this code solve this
  @override
  _YourPageState createState() => _YourPageState();

**Comment by agordn52** [comment]
Hi @jitendravn,

Since you have resolved this, I'll mark it complete.
