### ISSUE TITLE
Any plans for supporting GetX or RiverPod Packages in future

### ISSUE THREAD

**Issue by dvsgvarma** [nylo-core/nylo#13]
Any plans for adding GetX or RiverPod Package to Nylo or It would be great to know how our Ny*** are diff from them
https://pub.dev/packages/get
https://riverpod.dev/

**Comment by agordn52** [comment]
If you need to use these plugins, you can simply import them as a dependency in your project.

**Comment by jitendravaishnavs** [comment]
@agordn52 I have same question like
in nylo have its own extending own controller
what about getx controller

you was 
```Dart
class HomeController extends Controller {
}
```

and getx have
```Dart
class HomeController extends GetxController{}
```
 can use getx 
 your nylo have better performance feature

i'm little bit confuse

**Comment by agordn52** [comment]
Hi @jeetvaishnavnadol,

Here are the docs for [controllers](https://nylo.dev/docs/5.20.0/controllers) in Nylo.
If you want to use Getx you can import it as a dependency in your project.
