### ISSUE TITLE
After Auth.login() issue

### ISSUE THREAD

**Issue by jitendravn** [nylo-core/nylo#132]
flutter: error : FormatException: Unexpected character (at character 1)
Instance of 'User'
^

This is issue occurred
when hot restart my application
this error is form your 
![Screenshot 2024-04-27 at 5 22 57 PM](https://github.com/nylo-core/nylo/assets/93908273/651f33f4-7b6d-4049-abe6-892f84167ca5)

**Comment by agordn52** [comment]
Hi @jitendravn, 

I've just tested this and it works. 
I wasn't successful in replicating your error.

Please ensure you follow the [docs](https://nylo.dev/docs/5.20.0/authentication) to learn how to use authenticate in your project 👍
