### ISSUE TITLE
Router AuthPage false issue

### ISSUE THREAD

**Issue by jitendravn** [nylo-core/nylo#136]
```Dart
  router.route(
        LoginPage.path,
        (context) => LoginPage(),
        transition: PageTransitionType.fade,
        authPage: false,
      );
 ```     
Login page is not auth page
 but still i can redirected to LoginPage, even if AuthPage is false

**Comment by agordn52** [comment]
Hi @jitendravn,

`authPage` is used to define the initial page if the user is authenticated in your application.
Check out the docs to learn more https://nylo.dev/docs/5.20.0/authentication
