### ISSUE TITLE
nyPullToRefresh. updateState() Issue

### ISSUE THREAD

**Issue by jitendravn** [nylo-core/nylo#138]
_updateFeatureArticles() {
    updateState(
      "feature_articles",
    );
    StateAction.refreshPage('feature_articles');
    setState(() {});
  }

  _updateArticles() {
    StateAction.refreshPage('all_articles');

    updateState(
      "all_articles",
    );
    setState(() {});
  }
  
  Please do as soon as possible 
 not updating my state
 i have sent you a video on instagram
 please check

**Comment by jitendravn** [comment]
@agordn52 Have you find something.
cause  i have created new a project(with latest version of nylo) for checking
but same thing occurred

**Comment by agordn52** [comment]
Hi @jitendravn,

I'll take a look at my earliest convenience.

**Comment by agordn52** [comment]
Hi @jitendravn,

Can you try [5.27.2](https://pub.dev/packages/nylo_framework)?

Thanks

**Comment by jitendravn** [comment]
Sure, 
I will let you know If its working or not

**Comment by jitendravn** [comment]
Its working
when i use this StateAction.refreshPage('feature_articles');

not in UpdateState('feature_articles')

**Comment by agordn52** [comment]
Hi @jitendravn,

Ok great, glad to hear it's working.

Using `updateState` like that won't work unless you pass in `data` to update the state.

**Comment by jitendravn** [comment]
Got it, Thanks
