### ISSUE TITLE
update nylo_support

### ISSUE THREAD

**Issue by andim27** [nylo-core/nylo#140]
The last Flutter SDK use intl ver 0.19 
[flutter last intl version here](https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/pubspec.yaml)
The last nylo_support use ver 0.18.1
Please update nylo_support to intl 0.19

**Comment by agordn52** [comment]
Hi @andim27,

At the moment the latest stable version of Flutter is **3.19.6**.

If you click the below link you'll find that `flutter_localizations` requires intl `0.18.1`.
https://github.com/flutter/flutter/blob/3.19.6/packages/flutter_localizations/pubspec.yaml

It looks like `intl 0.19` will be added in **3.21.0**

https://github.com/flutter/flutter/blob/3.21.0-16.0.pre/packages/flutter_localizations/pubspec.yaml

We'll have to wait until then...
