### ISSUE TITLE
State management in page

### ISSUE THREAD

**Issue by tayfunuyar** [nylo-core/nylo#142]
Hi guys, 
How to update current state in page. 
stateUpdate not working in the page 

I give sample code update currency in current page state with setState why isn't working.
```
class ItemDetailPage
    extends NyStatefulWidget<ItemDetailController> {
  static const path = '/item-detail-page';
  static const stateName = "item-page-state";

  ItemDetailPage({super.key})
      : super(path, child: ItemDetailPageState());
}
class ItemDetailPageState
    extends NyState<ItemDetailPage> {
 String currency= 'EUR';

  ItemDetailPageState() {
    stateName = ItemDetailPage.stateName;
  }
  @override
  Widget view(BuildContext context) {
}
}
```

**Comment by agordn52** [comment]
Hi @tayfunuyar,

In your pubspec.yaml file, which version of nylo_framework are you using?

**Comment by tayfunuyar** [comment]
Hi @agordn52  
nylo_framework: ^5.27.2

**Comment by agordn52** [comment]
Ok great, try this https://nylo.dev/docs/5.20.0/state-management#updating-a-state

You can check out the full docs on https://nylo.dev or you can watch this video on state management in Nylo https://www.youtube.com/watch?v=X5EVh1KooFk

**Comment by agordn52** [comment]
Hi @tayfunuyar,

Try using the latest version of the [nylo_framework](https://pub.dev/packages/nylo_framework) and follow our documentation to help you understand how State Management works in Nylo.

**Comment by tayfunuyar** [comment]
Thanks @agordn52
