### ISSUE TITLE
Having Problem after auth.login and restart application

### ISSUE THREAD

**Issue by jitendravn** [nylo-core/nylo#143]
> [!CAUTION]
> flutter: error : FormatException: Unexpected character (at character 1)
Instance of 'User'
^

## Error come from
```Dart class AuthProvider implements NyProvider {
  @override
  boot(Nylo nylo) async {
    await event<SyncAuthToBackpackEvent>();

    return nylo;
  }

  @override
  afterBoot(Nylo nylo) async {}
}
```

@agordn52

**Comment by agordn52** [comment]
Hi @jitendravn,

Which `Model` are you trying to auth?
By default, Nylo will expect the model to be of Type `User`

**Comment by jitendravn** [comment]
@agordn52  User

**Comment by agordn52** [comment]
Hi @jitendravn,

In your `User` model have you correctly set up `toJson`? 

Also, in your `decoders.dart` file have you implemented  a `User` decoder?

**Comment by jitendravn** [comment]
@agordn52 But I'm Using Freezed for model

**Comment by agordn52** [comment]
> @agordn52 But I'm Using Freezed for model 

You need to implement a 'decoder' for the model and have a 'toJson' method if you want to use Auth in Nylo.

**Comment by jitendravn** [comment]
For now I have removed Freezed from my User model class
i have implemented this
class User extends Model{}
