### ISSUE TITLE
Having issue in api request 

### ISSUE THREAD

**Issue by SumitCodoffer** [nylo-core/nylo#144]
The request connection took longer than 0:00:05.000000 and it was aborted. To get rid of this exception, try raising the RequestOptions.connectTimeout above the duration of 0:00:05.000000 or improve the response time of the server.
![Screenshot 2024-05-14 at 2 39 44 PM](https://github.com/nylo-core/nylo/assets/169022283/d8081b50-05fb-43e0-9176-81aca744ff5c)

**Comment by agordn52** [comment]
Hi @SumitCodoffer,

Try using the `ApiService` like in the documentation [here](https://nylo.dev/docs/5.20.0/networking#base-options).

**Comment by SumitCodoffer** [comment]
i will use and let you know.
