### ISSUE TITLE
The method 'useErrorStack' isn't defined for the type 'Nylo'.

### ISSUE THREAD

**Issue by beingnitesh** [nylo-core/nylo#145]
Error (Xcode): lib/app/providers/app_provider.dart:32:10: Error: The method 'useErrorStack' isn't defined for the class 'Nylo'.

**Comment by agordn52** [comment]
Hi @beingnitesh,

In your `pubspec.yaml` file, which version of **nylo_framework** are you using?

Try running `flutter clean && flutter pub get`

**Comment by beingnitesh** [comment]
it is 5.20.0

**Comment by agordn52** [comment]
You'll need [5.27.4](https://pub.dev/packages/nylo_framework) to use `error_stack`

**Comment by agordn52** [comment]
Closing, please ensure you are on [5.27.4+](https://pub.dev/packages/nylo_framework) to use `error_stack`
