### ISSUE TITLE
NyPullToRefresh's empty widget while pull to refresh UI issue

### ISSUE THREAD

**Issue by SumitCodoffer** [nylo-core/nylo#146]
https://github.com/nylo-core/nylo/assets/169022283/3de62b4f-4d4b-4f35-bfad-91462f5cabe8

**Comment by agordn52** [comment]
Hi @SumitCodoffer,

I can't replicate your error, everything seems to be working.

![May-16-2024 17-47-33](https://github.com/nylo-core/nylo/assets/17294994/0fc82b55-3d53-477c-9a4b-b04e2c007923)

What does your code look like for the `NyPullToRefresh` widget?

**Comment by SumitCodoffer** [comment]
![Screenshot 2024-05-17 at 3 29 53 PM](https://github.com/nylo-core/nylo/assets/169022283/7744e5e5-a3a9-4e66-8db8-df8ae49be77a)

Here is the my code snippet.

**Comment by agordn52** [comment]
Hi @SumitCodoffer,

I've found that the issue only exists for Android. Very bizarre... I'll take a look into it.
![May-17-2024 17-35-11](https://github.com/nylo-core/nylo/assets/17294994/f5c06520-e8ca-4e34-badf-cee808174881)

Thanks for reporting this.

**Comment by agordn52** [comment]
@SumitCodoffer,

I've found that if you wrap your `empty` widget inside a `Container` or `SizedBox` it won't cause this issue.

Example below

```dart
NyPullToRefresh(
 child: (context, data) {
   return ListTile(
     title: Text(data),
   );
 },
 data: (page) async {
   return [];
 },
 empty: Container(
   height: 400,
     child: Center(child: Text("No data found"),),),
)
```
