### ISSUE TITLE
Can we have custom refresh load instead of this

### ISSUE THREAD

**Issue by jitendravn** [nylo-core/nylo#147]
![Screenshot 2024-05-24 at 3 36 57 PM](https://github.com/nylo-core/nylo/assets/93908273/fdb61f64-9338-4e5d-9c01-d7b9b45710ed)

**Comment by agordn52** [comment]
Hi @jitendravn,

Sorry for the late response.
I'll look into this.

**Comment by agordn52** [comment]
Hi @jitendravn,

Sorry for the late reply!
At the moment, you can use one of the following.

- ClassicHeader
- WaterDropHeader
- MaterialClassicHeader
- WaterDropMaterialHeader
- BezierHeader

``` dart
NyPullToRefresh(
    child: (context, item) {...},
    data: (page) async {...},
     headerStyle: "MaterialClassicHeader", // e.g. adding a header style
),
```

In the future, it'd be nice to implement custom headers.

**Comment by jitendravn** [comment]
Thank you @agordn52
