### ISSUE TITLE
Facing nested Routing issue in nylo

### ISSUE THREAD

**Issue by jitendravn** [nylo-core/nylo#149]
We are unable to use nested routing in Nylo.
example 
We have a floating bottom navigation bar with four items.
1 is a search page. 
When I click on the search page, it redirects me to the search page with the persistence of the bottom navigation bar.
and I also have one search button on the search page. and it's taking me to the search result page.
on that page. 
I'm not able to persist with my bottom navigation bar.

**Comment by agordn52** [comment]
Hi @jitendravn,

Do you mean route groups? https://nylo.dev/docs/5.20.0/router#route-groups

If you need to persist your bottom navigator bar it sounds like a programming problem to solve in your project, not an issue with Nylo.

Reopen if it's an issue with the Nylo framework, thanks
