### ISSUE TITLE
Check possible bug

### ISSUE THREAD

**Issue by andim27** [nylo-core/nylo#163]
Nylo ver ^5.32.6
if run: metro make:page my_page -c     
Then bug: 
no any added items at Map<Type, BaseController> controllers = {}//decoders.dart

**Comment by agordn52** [comment]
Hi @andim27,

You'll need to update it to `final Map<Type, dynamic> modelDecoders = {`
https://github.com/nylo-core/nylo/blob/5.x/lib/config/decoders.dart

Hope that helps.
