### ISSUE TITLE
Could not find package `ny_auth_slate` or file `ny_auth_slate:main`

### ISSUE THREAD

**Issue by birdycn** [nylo-core/nylo#167]
Thank you for providing such a great framework to help better learn and understand Flutter language.
I encountered a problem using the document 
`dart run nylo-framework: main slave: publish ny_outh_stlate` and the result shows: 
`Could not find package 'ny_outh_stlate' or file 'ny_outh_stlate': main`

**Comment by agordn52** [comment]
Hi @birdycn,

Thanks for your feedback 👍 

**Re. ny_auth_slate**
It looks like you ran the wrong command.
🚫 Don't use : `dart run nylo-framework: main slave: publish ny_outh_stlate`
✅ Use: `dart run ny_auth_slate:main publish:all`

Hope that helps
