### ISSUE TITLE
PageTransitionType.scale (with alignment) in routeTo

### ISSUE THREAD

**Issue by lacoste-sochi** [nylo-core/nylo#17]
Thank you for your efforts!

Please tell me how to apply 

PageTransitionType.scale (with alignment)

in routeTo(
 "/profile-page", 
 pageTransition: PageTransitionType.scale
 );
 

![image](https://user-images.githubusercontent.com/42961050/170699869-bbe5dbdd-4299-44fa-afce-719dfc38e3c0.png)

**Comment by agordn52** [comment]
Hi,

I'll investigate this later today.

Also, appreciate your feedback :)

**Comment by agordn52** [comment]
@lacoste-sochi 

You can now add an alignment using the `pageTransitionSettings` parameter.
```darta
routeTo("route-name", pageTransitionSettings: PageTransitionSettings(
        alignment: Alignment.center
    ));
```
