### ISSUE TITLE
docs site is broken for dark mode

### ISSUE THREAD

**Issue by dickermoshe** [nylo-core/nylo#174]
<img width="883" alt="image" src="https://github.com/user-attachments/assets/46953658-d41a-455a-9d54-47d84e79cd24">

**Comment by agordn52** [comment]
Hi @dickermoshe,

Thanks, I've pushed an update.
Let me know what you think.

**Comment by KhaledAlMana** [comment]
@agordn52 
Is this normal?

![image](https://github.com/user-attachments/assets/83a97f76-f6e4-4f6d-a748-da12959e7a0a)

**Comment by agordn52** [comment]
Thanks for spotting this @KhaledAlMana,

Should be fixed now
