### ISSUE TITLE
..

### ISSUE THREAD

**Issue by SumitCodoffer** [nylo-core/nylo#177]

**Comment by jitendravn** [comment]
> @agordn52 Using this command `# dart run nylo_framework:main make:page product_page`
> 
> Still have an old page structure
> 
> ``` dart
> class LoginPage extends NyStatefulWidget<LoginController> {
>   static const path = '/login';
> 
>   LoginPage({super.key}) : super(path, child: () => _LoginPageState());
> }
> 
> class _LoginPageState extends NyState<LoginPage> {
> 
>   /// [LoginController] controller
>   LoginController get controller => widget.controller;
> 
>   @override
>   init() async {
> 
>   }
> ```


@agordn52 I have seen your stub file in the framework repository. It's all fine. But when I try to make the page It's still the same as the older version have
