### ISSUE TITLE
 Could not resolve all files for configuration ':path_provider_android:androidJdkImage' with V6.1.2

### ISSUE THREAD

**Issue by alecoud** [nylo-core/nylo#178]
I made a fresh install of V6.1.2 and get the following error, is there any one can help? Thanks!

Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':path_provider_android:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':path_provider_android:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /Users/*****/Library/Android/sdk/platforms/android-34/core-for-system-modules.jar.
         > Error while executing process /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/jlink with arguments {--module-path /Users/*****/.gradle/caches/8.8/transforms/246e31b59c939962f5615691d4b70223-95426a75-025c-4349-8afb-f84ca83687ca/transformed/output/temp/jmod --add-modules java.base --output /Users/*****/.gradle/caches/8.8/transforms/246e31b59c939962f5615691d4b70223-95426a75-025c-4349-8afb-f84ca83687ca/transformed/output/jdkImage --disable-plugin system-modules}

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 6m 2s
Error: Gradle task assembleDebug failed with exit code 1

The below is flutter doctor result:

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.5 23F79 darwin-arm64, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.1)
[✓] VS Code (version 1.95.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

**Comment by agordn52** [comment]
Hi @alecoud,

Thanks for reporting this, it's now been resolved https://github.com/nylo-core/nylo/releases/tag/v6.1.3 ⚡️
