### ISSUE TITLE
Hidden Features and Recipes

### ISSUE THREAD

**Issue by lacoste-sochi** [nylo-core/nylo#18]
Hello everyone !

There are very few recipes using the framework.

For example, how do I check the saved token on the device, and transfer it to the router when downloading.

Some methods are not described in the documentation. For example, there is "handleSuccess", but the "handleFailure" method is not described. It is not clear how List<RouteGuard> works? routeGuards in routes. There are a lot of questions. Tell me that the project is not abandoned please )

UPD:
I made dependencies on checking the token and confirming the number in this way. I'm not sure if it's right, but everything works.
![image](https://user-images.githubusercontent.com/42961050/172388281-487066f7-6c7f-4612-805f-06ba0485d5ab.png)

**Comment by agordn52** [comment]
Hi @lacoste-sochi,

This project is not abandoned.

Re. the documentation 
I'll add extra docs to cover how the `handleFailure` works here - https://nylo.dev/docs/3.x/networking#understanding-the-network-helper 

Also, the implementation for 'checking the token' looks fine.
I'll close this issue now.
