### ISSUE TITLE
v6 error: updateState

### ISSUE THREAD

**Issue by andim27** [nylo-core/nylo#180]
1) download last(v6.2) nylo
2) add into HomePage after   get init => () async {} CODE:
```
  @override
  void stateUpdated(dynamic data) {
    print("HomePage stateUpdated: $data");
  }
```
3) add in list section CODE:

```
   ListTile(
      leading: FaIcon(FontAwesomeIcons.readme),
      title: Text(
        "Update state",
      ).bodyLarge(color: context.color.surfaceContent),
      subtitle: Text(
        "Page state",
      ).bodySmall(color: context.color.surfaceContent),
      trailing: const Icon(Icons.chevron_right),
      onTap: widget.controller.onTapMyAction,
    ),

```
4) add in HomeController:

 ```
 onTapMyAction() async {
    print("onTapMyAction works");
    updateState("/home", data: "Value from MyAction");
  }
```

results:
I/flutter (13645): onTapMyAction works_

**NO ANSWER in stateUpdated** 
**it NOT TRIGGER  stateUpdated(data)** 
p/s: it worked in v5

**Comment by agordn52** [comment]
Hi, I'll take a look at my earliest convenience

**Comment by agordn52** [comment]
This is resolved now, you'll need to ensure your pubspec.yaml file includes `nylo_framework: ^6.2.1`

In your `NyPage` use 
``` dart
class _HomePageState extends NyPage<HomePage> {

  @override
  get stateManaged => true;
```

This will allow you to use 
```
@override
  void stateUpdated(dynamic data) {
     ...
  }
```

One thing to note is that you should pass the `.path` of the page to like
``` dart
updateState(HomePage.path, data: ...);
```

**Comment by alecoud** [comment]
Hello @agordn52 , this approach worked before V6.3.6, but after update to the newest version V6.4.6, it doesn't work again, is there any modification with this in the updates?
