### ISSUE TITLE
Localization for the NyForm picker and datetime fields

### ISSUE THREAD

**Issue by alecoud** [nylo-core/nylo#186]
The NyForm picker and datetime fields use field name directly as the label text which is different than other fields and make it inconsistent for localization, it would be better if can translate the fields name here:

form_picker.dart
line 105: widget.field.name.titleCase
line 184: widget.field.name,
line 123: "${"Select".tr()} ${widget.field.name}", 

form_date_time_picker.dart
line 105: labelText: widget.field.name.titleCase,

**Comment by agordn52** [comment]
Hi @alecoud,

Thanks for reporting this, it's now been resolved in **nylo_framework** v6.2.9.

You can update your pubspec.yaml file to get these changes

``` yaml
nylo_framework: ^6.2.9
```
