### ISSUE TITLE
Docs error

### ISSUE THREAD

**Issue by andim27** [nylo-core/nylo#188]
State Management section:
```
  _SettingsTabState() {
    stateName = SettingsTab.state;
  }
```
Error code because in Nylo 6.2.9 correct code:
```
  _SettingsTabState() {
    stateName = SettingsTab.path.stateName();
  }
```
If generate page with "Metro" the  "static RouteView path ....." created

**Comment by agordn52** [comment]
Hi @andim27, 

The State Management section looks correct to me, it's for `NyState` not `NyPage`.

Maybe I'll add a section in https://nylo.dev/docs/6.x/state-management to explain how to use it with `NyPage` too 👍
