### ISSUE TITLE
How to use push notifications

### ISSUE THREAD

**Issue by wchbrad** [nylo-core/nylo#191]
I notice that the introduction says that 'It also comes with a ready-made file structure and setup, letting you start developing right away. Out the box, you'll have access to routing, localization, themes, local storage, push notifications, and more.' 
So how we use  push notifications?

**Comment by agordn52** [comment]
Hi @wchbrad,

Thanks for highlighting this.

The docs have now been updated on the nylo.dev. 
Here's a link to the new push notification section http://nylo.dev/docs/6.x/push-notifications
