### ISSUE TITLE
Play Store Rejection Risk Due to use exact alarm

### ISSUE THREAD

**Issue by ruwiss** [nylo-core/nylo#192]
I noticed your package uses the use exact alarm permission. According to Play Store policies, this permission is restricted to apps with core alarm/calendar functionality. This could cause issues for apps using your package that don't fall into these categories. Could you consider alternative approaches for scheduling notifications to avoid this restriction? Also, could you please provide guidance on how to override the default AndroidScheduleMode.exact setting?

**Comment by agordn52** [comment]
Hi @ruwiss,

Thanks for the [PR](https://github.com/nylo-core/support/pull/32). 

I've just merged this and it's in the latest release for the framework, the new default for androidScheduleMode is AndroidScheduleMode.exactAllowWhileIdle
