### ISSUE TITLE
When i build  iOS The method 'isBefore' isn't defined for the class 'TimeOfDay'.

### ISSUE THREAD

**Issue by azerioid** [nylo-core/nylo#193]
Error (Xcode): ../../.pub-cache/hosted/pub.dev/date_field-5.3.4/lib/src/widgets/adaptive_dialog.dart:47:11: Error: The method 'isBefore' isn't defined for the class 'TimeOfDay'.

Could not build the application for the simulator.
Error launching application on iPhone 16 Pro.

**Comment by agordn52** [comment]
Hi @azerioid,

`isBefore` isn't defined for the class `TimeOfDay`, that object doesn't have that method.

Use a `DateTime` object instead.

**Comment by azerioid** [comment]
It's first time run project return this error, I don't use any 3rd party package or change any code

**Comment by agordn52** [comment]
Hi @azerioid,

Try redownloading the project from nylo.dev and run it, that error shouldn't exist
