### ISSUE TITLE
How to change bottomNavigation to new Meterial 3 in Navigation Hub ?

### ISSUE THREAD

**Issue by srayleighdk** [nylo-core/nylo#194]
i want to change ui of bottomNavigation to  new design of Material 3, sorry my bad English. my version of Nylo is 6.4

**Comment by agordn52** [comment]
Hi @srayleighdk,

Make sure your theme is using `useMaterial3: true` in your `resources/themes/light_theme.dart`

``` dart
ThemeData lightTheme(ColorStyles color) {
  TextTheme lightTheme =
      getAppTextTheme(appFont, defaultTextTheme.merge(_textTheme(color)));

  return ThemeData(
    useMaterial3: true, 👈
```

**Comment by srayleighdk** [comment]
sorry for not clear question, 
![image](https://github.com/user-attachments/assets/cb60c5ae-207a-4804-9ce1-b532dfe49063)
i want this to NavigationBar how to change that, thank for reply me
