### ISSUE TITLE
Pwa ( Web problem ) 

### ISSUE THREAD

**Issue by jitendravn** [nylo-core/nylo#195]
![Screenshot 2024-12-19 at 1 06 25 PM](https://github.com/user-attachments/assets/26d74477-4bc6-496b-9615-a1b55433a82d)
Please check this
![Screenshot 2024-12-19 at 1 06 38 PM](https://github.com/user-attachments/assets/912606c0-be0a-4689-9077-7bf5a8e1abf7)

@agordn52

**Comment by jitendravn** [comment]
@agordn52 Please look into this issue fast

**Comment by jitendravn** [comment]
![Screenshot 2024-12-19 at 2 35 51 PM](https://github.com/user-attachments/assets/62c6bc80-c71a-41c1-93b6-51c583ebeb06)
@agordn52  Please also check this.

**Comment by agordn52** [comment]
Hi @jitendravn,

This should be resolved in `nylo_framework: ^6.4.3`
Please note that any `Cache` methods won't work with web at the moment 👍

**Comment by jitendravn** [comment]
@agordn52  One more thing. NyPullToRefresh is not working with PWA or web
