### ISSUE TITLE
Why is there still no progress for Provider

### ISSUE THREAD

**Issue by ruwiss** [nylo-core/nylo#198]
Why is there still no structure for Provider?
Writing functions on a view is a bad approach in Flutter. There is no fast method like notifyListeners on the controller.
A page is created and state update is done on the viewModel connected to it. This is the right approach. In 2022, I see that an “issue” was opened on this topic, but nothing was added. I like your package very much, I even made a 1+ hour long demo on YouTube. You can get inspired by another package called Stacked. It has a View - ViewModel structure and has nice methods.

**Comment by ruwiss** [comment]
```dart
class HomeController extends Controller {
  @override
  void construct(BuildContext context) {
    super.construct(context);
  }

  void onTapButton() {
    // Doesn't work
    showToastCustom(description: "test");

    // Works
    StateAction.showToastCustom(HomePage.path, description: "test");

    // Works
    state.dump();
  }
}

```
At least this should work

```dart

class HomePage extends NyStatefulWidget<HomeController> {
  static RouteView path = ("/home", (_) => HomePage());

  HomePage({super.key}) : super(child: () => _HomePageState());
}

class _HomePageState extends NyPage<HomePage> {
  @override
  get init => () async {};

  /// Define the Loading style for the page.
  /// Options: LoadingStyle.normal(), LoadingStyle.skeletonizer(), LoadingStyle.none()
  @override
  LoadingStyle get loadingStyle => LoadingStyle.normal();

  @override
  bool get stateManaged => true;

  @override
  void stateUpdated(data) async {
    super.stateUpdated(data);
    "123".dump();
  }

  /// The [view] method displays your page.
  @override
  Widget view(BuildContext context) {
    return Scaffold(
      body: SafeAreaWidget(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Logo(),
              Text(
                getEnv("APP_NAME"),
              ).displayMedium(color: context.color.content),
              Gap(20),
              ThemeToggle(),
              Gap(20),
              Button.primary(
                text: "Test",
                onPressed: () => widget.controller.onTapButton(),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

state is printed but there is no change

With HomePage.path I have to specify path every time.
```dart
StateAction.showToastCustom(HomePage.path, description: "test");
```
but it's already connected to HomePage and why would that be needed?

**Comment by agordn52** [comment]
Hi @ruwiss,

Sorry if I've misunderstood but there is a structure to Providers in Nylo, heres the docs https://nylo.dev/docs/6.x/providers

Re. Writing functions on a view is a bad approach in Flutter
You can organize your project to use MVC, Nylo supports controllers where you can add methods related to your view in there.

Lastly, on the issue you've spotted, I'll take a look and investigate 🙂
Thanks for your support and if you have any ideas to contribute to the framework, feel free to send a PR

**Comment by ruwiss** [comment]
That's not the provider I'm talking about, I'm talking about ChangeNotifier.
https://pub.dev/packages/provider

Why can't I update state via controller?

State name does not work, I need to specify the page path

```dart
    // Doesn't work
    showToastCustom(description: "test");

    // Works
    StateAction.showToastCustom(HomePage.path, description: "test");
```

**Comment by agordn52** [comment]
Hi @ruwiss, 
That package has nothing to do with Nylo but if you want to use it, you can 🙂 `flutter pub add provider`
If you have ideas to improve how state management is handled, feel free to send a PR

Re. Why can't I update state via controller?
I've mentioned in my last message: "Lastly, on the issue you've spotted, I'll take a look and investigate 🙂"

**Comment by ruwiss** [comment]
My English is bad so I didn't understand your last words sorry.
If I specify it as HomePage.path it works. However, if I specify it as state, it does not work.
When I change the stateName via HomePage, it still doesn't work.

If this problem is solved, there will be no need to use additional packages.
I'm also trying to understand the problem

**Comment by agordn52** [comment]
Hi @ruwiss,

I've just tried this today and it appears to work as expected.

Can we arrange a quick Google Meet call to see what's happening?
You can send me a message on IG https://www.instagram.com/agordn

**Comment by ruwiss** [comment]
I’d love to have a Google Meet with you, but unfortunately, I don’t speak English and had to write this message using AI 😄.

To explain the changes I made:
I wanted to update any page connected to the Controller directly from the Controller itself, but I couldn’t manage to do so. However, I noticed that it works when I pass the path value of the page whose state I want to update into the StateAction function. It didn’t work if I passed the state value instead of the path.

I ran your package locally and compared how the state name appeared in the logs. I noticed that there was an extra “Closure” text. Once I removed this text, it worked as I intended. Now, pages connected to the Controller can be easily updated.

Additionally, I added the familiar notifyListeners for state management. There was a small logical issue: if the function provided inside setState(() {}) wasn’t simple, the state wouldn’t update. To fix this, I executed the function first and then ran the setState function. With this adjustment, it now works as expected.

I wanted to use your package in one of my projects and made some adjustments to fit my needs.

I also created an extension for VS Code, so users can utilize your package through the extension instead of the CLI:
https://marketplace.visualstudio.com/items?itemName=ruwiss.nylo-micro-framework
repo: https://github.com/ruwiss/nylo_vsce it yours :)

**Comment by agordn52** [comment]
@ruwiss,

No worries, maybe we can still connect on Google meet and translate via AI 😅

Oh and the VS Code extension looks amazing!! Wow, I will definitely try this and maybe add it to the nylo.dev docs.
I'll send you a message on Instagram.

**Comment by ruwiss** [comment]
😄😄 Thank you
Instagram: https://www.instagram.com/ruwis.io/

**Comment by andim27** [comment]
As I understood The question is about:
1) separate View-Controllel logics
2) reactive controller which contains logics and has ability o change variable in View from controller
It would be nice to have these features in future releases.
