### ISSUE TITLE
Make BaseNavigationHub index globally changeable 

### ISSUE THREAD

**Issue by B3K4682** [nylo-core/nylo#200]
I am facing an issue where I need to programmatically change the currently active tab in the BottomBar when a button is pressed. Despite searching through the documentation and community, I have not been able to find a solution or workaround to achieve this.

**Expected Behavior**:
When a button is pressed, the **BottomBar** should update the active tab, reflecting the change visually and updating the displayed content accordingly.

**Current Behavior**:
Currently, there is no way to change the active tab of the **BottomBar** through a button press, resulting in a lack of interactivity and the inability to control the tab programmatically.

If anyone has a recommended approach or workaround for programmatically changing the BottomBar tab upon button press, I would appreciate any suggestions. Alternatively, if there are any known issues or limitations with this functionality, please let me know.

**Comment by agordn52** [comment]
@B3K4682,

Thanks for reporting this. I'll take a look tomorrow. If the functionality already exists, I'll update the docs on the nylo.dev website and inform you here.

**Comment by agordn52** [comment]
Hi @B3K4682,

I've added a feature into the framework to allow you to do this, in `nylo_framework ^6.5.2` you can now use.

``` dart
BaseNavigationHub.stateActions.currentTabIndex(theTab);

// Example
BaseNavigationHub.stateActions.currentTabIndex(2);
```

**Comment by B3K4682** [comment]
Thank you! 🚀🎉
