### ISSUE TITLE
Please write a demo of MVVM

### ISSUE THREAD

**Issue by bxlkm** [nylo-core/nylo#28]
goodjob！

**Comment by agordn52** [comment]
MVVM is an architectural pattern so this isn't an issue.
If you want to learn about MVVM, here's a link 👍https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel#:~:text=Model%E2%80%93view%E2%80%93viewmodel%20(MVVM,is%20not%20dependent%20on%20any
