### ISSUE TITLE
Is there a setting similar to global management of application state?

### ISSUE THREAD

**Issue by jet10000** [nylo-core/nylo#29]
Like this

https://starlite-api.github.io/starlite/usage/0-the-starlite-app/2-using-application-state/

Or how can I implement something like this, or use nylo routes to pass state data between pages?

**Comment by agordn52** [comment]
I'm not familiar with that library but if you need to pass a state there are a few ways you could achieve this in Flutter.
In Nylo, I think this method would work https://nylo.dev/docs/3.x/router#passing-data-to-another-page

I'll close this as it's not an issue with the Nylo micro-framework.
Open a discussion here instead https://github.com/nylo-core/nylo/discussions or try StackOverflow :)
