### ISSUE TITLE
How to update from Nylo v3.0.3 to v3.2.1

### ISSUE THREAD

**Issue by jet10000** [nylo-core/nylo#30]
The documentation does not document how to implement the update.

**Comment by agordn52** [comment]
I'll add some docs to https://nylo.dev 👍
I'll ping a notification here once it's live.

**Comment by agordn52** [comment]
Hi @jet10000,

Here's the differences between v3.0.3 and v3.2.1
https://github.com/nylo-core/nylo/compare/v3.0.3...v3.3.0#diff

I might start adding this link to the docs to help with upgrades.
Hope that helps :)
