### ISSUE TITLE
How to get response message onError ?

### ISSUE THREAD

**Issue by taufiqridha** [nylo-core/nylo#33]
Hi, how i can get error message from server using API service ?

<img width="560" alt="Screen Shot 2022-09-11 at 22 27 04" src="https://user-images.githubusercontent.com/1453050/189535784-48191d31-c913-40df-8c3a-f16fb1ed11d1.png">

calling via controller 

<img width="458" alt="Screen Shot 2022-09-11 at 22 24 56" src="https://user-images.githubusercontent.com/1453050/189535690-5ca218ce-7b76-4b17-9d17-6752ecfd7aad.png">
many thanks for assist..

**Comment by agordn52** [comment]
Hi @taufiqridha,

In your APIService, you can override one of the following methods.

```dart
/// Handle the [DioError] response if there is an issue.
onError(DioError dioError) {}

/// Display a error to the user
/// This method is only called if you provide the API service
/// with a [BuildContext].
displayError(DioError dioError, BuildContext context) {}
```

Hope that helps.

**Comment by taufiqridha** [comment]
I see there's a function onError but somehow i cant catch them inside my call.
So i created on handleFailure on network, and throw them, so i can access on my catch

```
handleFailure: (DioError err) {
          throw err;
});
```

```
try {
      MeModel? me =
          await api<ApiService>((request) => request.login(username, password));
      if (me != null) {
       // ok
        print(me)
      }
     
    } on DioError catch (e) {
      //catch here works
      print(e)
    }

```

thanks for assist @agordn52 . We can close this
