### ISSUE TITLE
Broken link to collection library in documentation

### ISSUE THREAD

**Issue by Stormheg** [nylo-core/nylo#34]
On https://nylo.dev/docs/3.x/what-is-nylo

In the framework dependencies section, the link to the [collection](https://github.com/flutter/collection) library is broken.

**Comment by agordn52** [comment]
Hi @Stormheg, thanks for spotting this 👌
I've just pushed a fix here for the docs https://github.com/nylo-core/nylo.dev/commit/ddb12438ceb35b5b1f6e8e2dd0d44b8401ffdd0f

**Comment by Stormheg** [comment]
Amazing! Thanks for fixing that so quick 👍
