### ISSUE TITLE
State Management

### ISSUE THREAD

**Issue by AdemAygun** [nylo-core/nylo#38]
### Discussed in https://github.com/nylo-core/nylo/discussions/37

<div type='discussions-op-text'>

<sup>Originally posted by **AdemAygun** December 17, 2022</sup>
Hi ,
I'm new to flutter.  I've been reviewing nylo framework recently. Nylo is good job. 
It caught my attention that no package related to state management was used. Nylo uses NyState and NyStatefulWidget instead of other state management packages. (In this [link ](https://blog.gskinner.com/archives/2020/09/flutter-state-management-with-mvcs.html), he used MVC+S pattern like nylo with state management )

Do you consider to add a milestone about state management(provider, bloc flutter,or riverpod ) in nylo framework ?
</div>

**Comment by agordn52** [comment]
Answered
