### ISSUE TITLE
Suggestion: Add an env.dart file

### ISSUE THREAD

**Issue by junevm** [nylo-core/nylo#46]
```
import 'package:nylo_framework/nylo_framework.dart';

class Env {
  static String API_BASE_URL = getEnv('API_BASE_URL');
}

```

will help in ide autocomplete for env var

**Comment by agordn52** [comment]
Hi @a0v0,

I've already given you an answer on this last month https://github.com/nylo-core/nylo/pull/41

If you really need autocomplete, build a plugin for your IDE. That would be the best option.
