### ISSUE TITLE
Cant use fontweightBold()

### ISSUE THREAD

**Issue by junevm** [nylo-core/nylo#47]
Happening with latest version

```
 child: Text(
                    trans("auth.get_started"),
                  ).fontWeightBold(),
```

getting this

![image](https://user-images.githubusercontent.com/62926341/222815464-a053849a-7204-46d0-b968-c3832faa8f5b.png)

**Comment by junevm** [comment]
But working with 

```
child: Text(
                    trans("auth.get_started"),
                    style: const TextStyle(),
                  ).fontWeightBold(),
```

**Comment by agordn52** [comment]
Hi @a0v0, [v4.3.1](https://github.com/nylo-core/nylo/releases/tag/v4.3.1) fixes the above issues.

There's been an update in the `bootstrap/extensions.dart` file https://github.com/nylo-core/nylo/blob/4.x/lib/bootstrap/extensions.dart
