### ISSUE TITLE
primaryColor not reflecting in input field color

### ISSUE THREAD

**Issue by junevm** [nylo-core/nylo#48]
I have set primaryColor value to blue. But the input field label color is purple. 

How do I make input field to inherit this blue color?

![image](https://user-images.githubusercontent.com/62926341/222821487-df30dbc7-5d5d-4601-9304-aa68f2683214.png)

**Comment by agordn52** [comment]
Hi @a0v0, 

You can change the label colour from your light/dark theme file like in the below example.

```dart
return ThemeData(
  ...
  inputDecorationTheme: const InputDecorationTheme(
    labelStyle: TextStyle(color: Colors.black),
  )
```
