### ISSUE TITLE
Theme font

### ISSUE THREAD

**Issue by chrisvidal** [nylo-core/nylo#5]
Really love the concept of this framework and I am testing it on a project. Thanks for the good stuff.

`final TextStyle appThemeFont = GoogleFonts.montserrat();`

How can I switch the google font to a TTF font available from my assets folder in the theme file?

**Comment by agordn52** [comment]
Hi Chris,

Thanks for your initial feedback.

If you want to use a custom font in your project, you can use the `TextStyle` class like the below example.
``` dart
// file: lib/config/app_theme.dart
...
TextStyle appThemeFont = TextStyle(fontFamily: "ZenTokyoZoo");
```

Just make sure that the "**fontFamily**" has been added to your `pubspec.yaml` file as per the flutter cookbook example. https://flutter.dev/docs/cookbook/design/fonts#2-declare-the-font-in-the-pubspec
