### ISSUE TITLE
NyText extension

### ISSUE THREAD

**Issue by andim27** [nylo-core/nylo#53]
A member named 'bodyMedium', 'bodyLarge' etc... is defined in extension 'NyText' and extension 'NyText', and none are more specific.
Questions: why? what to do if I have a project based on prev version?

**Comment by agordn52** [comment]
Hi, you can remove the NyText extensions from extension.dart file as they are apart of the framework. 

Check out this commit to learn more.
https://github.com/nylo-core/nylo/commit/58e6ff068b856ace4eb6b144f7799a2285efca61

Thanks,
Anthony
