### ISSUE TITLE
Latest v5.0.5 fails to install dependencies when running `flutter pub get`

### ISSUE THREAD

**Issue by ian-wd** [nylo-core/nylo#54]
Must have pushed a development related dependency

```
Because flutter_app depends on laravel_auth_slate from path which doesn't exist (could not find package laravel_auth_slate at "/Users/anthony/StudioProjects/slate_template_laravel_auth"), version solving failed
```

**Comment by agordn52** [comment]
Hi @ian-wd,

Thanks for highlighting this! 

Sorry, this was an accident, resolved in [v5.0.6](https://github.com/nylo-core/nylo/releases/tag/v5.0.6).
The change is to remove laravel_auth_slate from your pubspec.yaml like in the example [here](https://github.com/nylo-core/nylo/commit/c4d7f093a7a7c2eb486d9aed541fbea5743722e3).
