### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by chrisvidal** [nylo-core/nylo#6]
I am working with flutter sdk 2.12.0 and above.

is it a plan on your side to refactor the method `Appbuild()` in `bootstrap/app.dart`?
It is currently causing some type and null safety issue

**Comment by agordn52** [comment]
Hi Chris, 

[`v1.1.0`](https://github.com/nylo-core/nylo/releases/tag/v1.1.0) now works with Flutter SDK 2.12.0 out the box 🥳
