### ISSUE TITLE
onGenerateRoute + ResponsiveFramework

### ISSUE THREAD

**Issue by lpdevit** [nylo-core/nylo#72]
Hi,
I'm trying to use Nylo + [ResponsiveFramework](https://github.com/Codelessly/ResponsiveFramework)
I was looking at [this example](https://github.com/Codelessly/FlutterMinimalWebsite/blob/700a90d68f003e10aa90e6f1b45fc5c220899787/lib/main.dart) but I have a problem...
How can I use their "onGenerateRoute" with Nylo:

```
runApp(
    AppBuild(
      navigatorKey: NyNavigator.instance.router.navigatorKey,
      onGenerateRoute: nylo.router!.generator(), // THIS ROW!!!
      debugShowCheckedModeBanner: false,
      initialRoute: nylo.getInitialRoute(),
    ),
  );
```

Thank you for your help! If this is the wrong place to ask, I'm sorry and please tell me where I can get help

**Comment by agordn52** [comment]
Hi @lpdevit,

I've got an idea to make this work for you.

What we could do is change the `nylo.router!.generator()` method to accept an optional callback which would contain the widget returned from the generator. 

This would then allow you to override the default widget returned.

I'll get to work on the concept and reply back when I've got news.

**Comment by lpdevit** [comment]
> Hi @lpdevit,
> 
> I've got an idea to make this work for you.
> 
> What we could do is change the `nylo.router!.generator()` method to accept an optional callback which would contain the widget returned from the generator.
> 
> This would then allow you to override the default widget returned.
> 
> I'll get to work on the concept and reply back when I've got news.

Hello Anthony, that'd be great! Thank you for your help! Please let me know when it'll be ready to test
Have a nice day
:)

**Comment by agordn52** [comment]
Hi @lpdevit,

You'll now be able to do something like below using nylo_framework [5.3.6](https://pub.dev/packages/nylo_framework/versions)
``` dart
onGenerateRoute: nylo.router!.generator(builder: (context, widget) {
        return BouncingScrollWrapper.builder(
            context, widget,
            dragWithMouse: true);
      }),
```

Hope that helps 🔥

**Comment by lpdevit** [comment]
> Hi @lpdevit,
> 
> You'll now be able to do something like below using nylo_framework [5.3.6](https://pub.dev/packages/nylo_framework/versions)
> 
> ```dart
> onGenerateRoute: nylo.router!.generator(builder: (context, widget) {
>         return BouncingScrollWrapper.builder(
>             context, widget,
>             dragWithMouse: true);
>       }),
> ```
> 
> Hope that helps 🔥

Thank you Anthony, it works great!
Have a nice day :)
