### ISSUE TITLE
How to override Dio baseoptions?

### ISSUE THREAD

**Issue by keremkurtulus** [nylo-core/nylo#73]
I couldn't override `connectTimeout` value in BaseOptions of Dio in NyBaseApiService class. Could you assist me to do that correctly? 

In that class baseoptions initialized in the init method
```
  void init() {
    baseOptions = BaseOptions(
      baseUrl: baseUrl,
      headers: {
        "Content-type": "application/json",
        "Accept": "application/json",
      },
      connectTimeout: Duration(seconds: 5),  <!-- here
    );

    _api = Dio(baseOptions);

    if (useInterceptors) {
      _addInterceptors();
    }
  }
```

**Comment by agordn52** [comment]
Hi @keremkurtulus,

You should be able to do this https://nylo.dev/docs/5.x/networking#base-options

Hope that helps.

**Comment by keremkurtulus** [comment]
> Hi @keremkurtulus,
> 
> You should be able to do this https://nylo.dev/docs/5.x/networking#base-options
> 
> Hope that helps.

Hello @agordn52, thanks for your reply. Isn't the init method in NyBaseApiService class overwriting the baseOptions?

**Comment by agordn52** [comment]
Hi, no problem and `init` is called in the constructor. 
If you use the example in the docs it should work fine.
