### ISSUE TITLE
need more documentations/examples

### ISSUE THREAD

**Issue by jagdishjadeja** [nylo-core/nylo#8]
- need more documentation on complex scenarios like nested route, state management
- is there any discord/slack server where devs can ask support questions?
- is there any complex app examples  ? chat app, e-commerce app, todo ?
- how to contribute ?
- what is future roadmap ?

**Comment by agordn52** [comment]
Hi, here are some answers to your queries.
**Q: need more documentation on complex scenarios like nested route, state management**
A: More documentation is coming soon via the https://nylo.dev

**Q: is there any discord/slack server where devs can ask support questions?**
It's an open-source project so hopefully, with time, more faqs will be on sites like StackOverflow.

**Q: is there any complex app examples ? chat app, e-commerce app, todo ?**
A: Yes, here's one https://github.com/woosignal/flutter-woocommerce-app. More examples to come soon too.

**Q: how to contribute ?**
A: It's an open-source project so feel free to create a PR for anyone of the following repos that Nylo uses:
- https://github.com/nylo-core/nylo
- https://github.com/nylo-core/framework
- https://github.com/nylo-core/support

**Q: what is future roadmap ?**
A: At the moment continuing to maintain the repos. A long term roadmap is coming soon.

**Comment by chrisvidal** [comment]
currently, nylo is state management (such as Bloc, Provider, Riverpod, etc...) solution free, is it in the roadmap to integrate any one of them?
