### ISSUE TITLE
NyTextField

### ISSUE THREAD

**Issue by RoxDevvv** [nylo-core/nylo#81]
am using NyTextField it works well however how could I know if all fields are correct when I press submit button 
Thank you

**Comment by agordn52** [comment]
Hi @RoxDevvv,

You can create a function in the Widget and use the `validate` helper to check the data 👍
``` dart
// Example
_login() {
    String emailExample = 'anthony@web.com';

    validate(rules: {
      "email address": "email" // validation rule 'email'
    }, data: {
      "email address": emailExample
    }, onSuccess: () {
      print('looks good');
      // do something...
    });
}
```

Check out the docs to learn [more](https://nylo.dev/docs/5.x/validation)
