### ISSUE TITLE
Router extend

### ISSUE THREAD

**Issue by andim27** [nylo-core/nylo#84]
Need the ability to get the previous route name
Something like this: `NyRouter().getPreviousRouteName()`

**Comment by agordn52** [comment]
Hi @andim27,

I'll explore this over the weekend.

**Comment by agordn52** [comment]
Hi @andim27,

I'm still thinking about this one. Let's move it into [discussions](https://github.com/nylo-core/nylo/discussions) tab instead of 'issues'. If you have any ideas for it too just let me know.

Thanks,
