### ISSUE TITLE
localization is broken

### ISSUE THREAD

**Issue by RoxDevvv** [nylo-core/nylo#85]
i spend hours trying to make it work as expected but it has a lot of issues, especially in RTL languages 
nylo localization restarting the whole app and even after restarting UI doesn't switch to RTL 
I end up using [https://pub.dev/packages/easy_localization](url) however I wich those problems get a fix 

what we need Localization should happen without restarting the app and rtl UI should refresh

**Comment by agordn52** [comment]
Hi @RoxDevvv,

The `Text` widgets will need to be updated throughout the app if the user changes locale.

Re. RTL
At the moment, the micro-framework doesn't fully support this out of the box.
If you/anyone has ideas to implement this nicely, feel free to send a PR.
