### ISSUE TITLE
build fails in nylo 5.11.0

### ISSUE THREAD

**Issue by Im-PJ** [nylo-core/nylo#87]
After updating nylo from 5.8.0 to 5.11.0, my ios build fails with this error 
Error (Xcode): ../../.pub-cache/hosted/pub.dev/nylo_support-5.17.0/lib/helpers/extensions.dart:264:7: Error: Type 'TextScaler' not found.

any dependent package needs to be updated?

**Comment by agordn52** [comment]
Hi @Im-PJ, which version of Flutter are you using? 

You might need to upgrade.

**Comment by Im-PJ** [comment]
sorry thanks
