### ISSUE TITLE
Build failed TextScaler not found error

### ISSUE THREAD

**Issue by jitendravn** [nylo-core/nylo#91]
./../../.pub-cache/hosted/pub.dev/nylo_support-5.18.0/lib/helpers/extensions.dart:264:7: Error: Type 'TextScaler' not found.
      TextScaler? textScaler,
      ^^^^^^^^^^

flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d211f42860 (5 weeks ago) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0

**Comment by agordn52** [comment]
Hi @jitendravn,

I think this is related to this issue https://github.com/nylo-core/nylo/issues/87 👍
