### ISSUE TITLE
Auth Guard not working

### ISSUE THREAD

**Issue by DesmondLouis** [nylo-core/nylo#98]
I configured an Auth guard and seems it is not even called 
![image](https://github.com/nylo-core/nylo/assets/17048035/93ca0d04-314d-48ab-8363-a38ee26e23cb)

**Comment by agordn52** [comment]
Hi @DesmondLouis,

If you use `routeTo` instead of `Navigator.pushNamed`, it should work.

In a future release of Nylo it would be nice if it also worked with that method too.

**Comment by DesmondLouis** [comment]
Hi @agordn52,
Thanks for your response I found that and was preparing to close the issue. 
I will be great if it is stated in the documentation. Any ways thanks

**Comment by agordn52** [comment]
No problem :) 

<ins>Re. the docs</ins> 
I'll get them updated.

Thanks 👍
